### ISSUE TITLE
UserId and Password parameters are missing

### ISSUE THREAD

**Issue by amarcobal** [GustavoAmerico/SQLServerDeploy#16]
I have an error while trying to perform a deployment related to anonymous login:

`System.Data.SqlClient.SqlException: Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'`

Checking the code I have seen that the UserId and Password parameters are not included in the publishing command.

https://github.com/GustavoAmerico/SQLServerDeploy/blob/fc91257e858acb7478862bc1c3d3c1bf75c9624a/src/AzureDevOps/SQLServerDeploy/Tasks/MSSQLDeploy/command.ps1#L130

The correct command should be:

` &$dacpac publish --DacPath=$dacpacPath --server=$server --namePattern=$dacpacPattern  --databaseNames=$dbName --userId=$userId --password=$password --blockOnPossibleDataLoss=$blockOnPossibleDataLoss --verifyDeployment=$verifyDeployment --compareUsingTargetCollation=$compareUsingTargetCollation --allowIncompatiblePlatform=$allowIncompatiblePlatform --commandTimeout=$commandTimeout --createNewDatabase=$createNewDatabase`

Can you fix it?

Thanks!

**Comment by GustavoAmerico** [comment]
https://github.com/GustavoAmerico/DacpacToolCli/pull/1
