### ISSUE TITLE
On Prem Deploy PS Error

### ISSUE THREAD

**Issue by ghost** [GustavoAmerico/SQLServerDeploy#5]
We are receiving the error "##[error]System.Management.Automation.PSInvalidOperationException: Data line 'false' is not in 'name=value' format. " when deploying to on prem sql server 2017.  The DB and/or DB changes are published, so it appears to be working but still throwing an error.

The reason this occurs is due to "False" being autopopulated in the "Variables for the database deployment" section of the extension.  Removing "False" causes the error to go away.

**Comment by GustavoAmerico** [comment]
It's is released in 2.*. Please, update you task
